# Generated by Django 3.2.12 on 2024-01-13 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('u', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='plan',
            field=models.CharField(choices=[('Бизнес', 'Бизнес'), ('Образование', 'Бизнес')], default='w', max_length=20),
            preserve_default=False,
        ),
    ]
